import {createRequire} from 'node:module';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {createServer} from 'node:http';
import {spawn} from 'node:child_process';
const require=createRequire('/home/tester/code/CopilotKit/OpenDots/package.json');const {chromium}=require('playwright');
const root='/home/tester/evidence/integration-audit',out=root+'/direct';mkdirSync(out,{recursive:true});
const key=JSON.parse(readFileSync(root+'/voice-session.json')).api_key;
const events=[],checks=[],audio=[];let rms=0,maxRms=0,bytes=0,lastSound=0;
const server=createServer((req,res)=>res.end('<button id="start">Start voice test</button>'));await new Promise(r=>server.listen(14700,'127.0.0.1',r));
const browser=await chromium.launch({headless:false,ignoreDefaultArgs:['--mute-audio'],env:{...process.env,PULSE_SOURCE:'jarvis_mic',PULSE_SINK:'voice_output'}});
const ctx=await browser.newContext({permissions:['microphone']});const p=await ctx.newPage();await p.goto('http://localhost:14700');
await p.exposeFunction('captureEvent',e=>{events.push({at:Date.now(),...e});if(['error','conversation.item.input_audio_transcription.completed','response.done'].includes(e.type))console.log('EVENT',e.type,e.transcript??e.response?.status??JSON.stringify(e.error));});
const rec=spawn('parec',['--device=voice_output.monitor','--raw','--format=s16le','--rate=24000','--channels=1']);rec.stdout.on('data',b=>{audio.push(b);bytes+=b.length;let sum=0;for(let i=0;i+1<b.length;i+=2)sum+=(b.readInt16LE(i)/32768)**2;rms=Math.sqrt(sum/(b.length/2));maxRms=Math.max(maxRms,rms);if(rms>.01)lastSound=Date.now();});
const auth={Authorization:'Bearer '+key};
async function req(path,method='POST',body,headers={}){return fetch('http://127.0.0.1:18800'+path,{method,headers:{...auth,...headers},body,signal:AbortSignal.timeout(35000)});}
function assert(ok,msg){if(!ok)throw new Error(msg);}
async function wait(fn,ms=45000){const start=Date.now();while(Date.now()-start<ms){if(await fn())return;await p.waitForTimeout(100);}throw new Error('condition timed out');}
async function speak(name){console.log('MIC',name);await new Promise((resolve,reject)=>{const c=spawn('paplay',['--device=voice_input','/home/tester/evidence/'+name+'.wav']);c.on('exit',code=>code===0?resolve():reject(new Error('paplay '+code)));});}
const session={type:'realtime',model:'qwen2.5:7b-instruct-q4_K_M',output_modalities:['audio'],instructions:'You are a concise voice assistant. Answer briefly.',audio:{input:{transcription:{model:'gpt-4o-mini-transcribe'},turn_detection:{type:'semantic_vad',create_response:true,interrupt_response:true}},output:{voice:'af_heart'}}};
let location;
async function connect(){const n=events.length;const sdp=await p.evaluate(async()=>{window.pc=new RTCPeerConnection();window.stream=await navigator.mediaDevices.getUserMedia({audio:true});window.player=new Audio();window.pc.ontrack=e=>{window.player.srcObject=e.streams[0];window.player.play().catch(e=>window.captureEvent({type:'playback.error',message:e.message}));};window.stream.getTracks().forEach(t=>window.pc.addTrack(t,window.stream));window.dc=window.pc.createDataChannel('oai-events');window.dc.onmessage=e=>window.captureEvent(JSON.parse(e.data));const offer=await window.pc.createOffer();await window.pc.setLocalDescription(offer);return offer.sdp;});const response=await req('/v1/realtime/calls','POST',sdp,{'Content-Type':'application/sdp'});assert(response.ok,'call setup HTTP '+response.status);location=response.headers.get('location');const answer=await response.text();await p.evaluate(async({answer,session})=>{window.dc.onopen=()=>window.dc.send(JSON.stringify({type:'session.update',session}));await window.pc.setRemoteDescription({type:'answer',sdp:answer});},{answer,session});await wait(()=>events.slice(n).some(e=>e.type==='session.updated'));await wait(()=>p.evaluate(()=>window.pc.connectionState==='connected'));return n;}
async function close(){await p.evaluate(()=>{window.stream?.getTracks().forEach(t=>t.stop());window.pc?.close();window.player?.pause();});}
async function check(name,fn){console.log('CASE',name);const start=Date.now();try{const details=await fn();checks.push({name,result:'PASS',seconds:(Date.now()-start)/1000,details});console.log('PASS',name);}catch(e){checks.push({name,result:'FAIL',error:e.message});throw e;}}
try{
await p.click('#start');
await check('rejected SDP releases capacity for retry',async()=>{const r=await req('/v1/realtime/calls','POST','v=0\r\nm=audio 9 RTP/AVP 0',{'Content-Type':'application/sdp'});assert(!r.ok,'malformed SDP accepted');return{status:r.status};});
await check('direct native microphone and audible answer',async()=>{const n=await connect();maxRms=0;await speak('opendots-question');await wait(()=>events.slice(n).some(e=>e.type==='response.output_audio_transcript.done'&&/\b(?:twelve|12)\b/i.test(e.transcript)));await wait(()=>maxRms>.01);await wait(()=>Date.now()-lastSound>1500);return{speakerPeakRms:maxRms,sessionAcknowledged:true};});
await check('peer disconnect then fresh call on same reservation',async()=>{await close();await p.waitForTimeout(2500);await connect();await close();return{reconnected:true};});
await check('repeat reconnect and actual spoken interruption',async()=>{await p.waitForTimeout(2500);const n=await connect();await speak('opendots-long');await wait(()=>rms>.01);await p.waitForTimeout(1000);const interruptAt=Date.now(),audioSeconds=bytes/48000;await speak('opendots-interrupt');await wait(()=>events.slice(n).some(e=>e.type==='response.output_audio_transcript.done'&&/Paris/i.test(e.transcript)),65000);const reply=events.slice(n).find(e=>e.type==='response.output_audio_transcript.done'&&/Paris/i.test(e.transcript));await wait(()=>events.slice(n).some(e=>e.type==='output_audio_buffer.stopped'&&e.response_id===reply.response_id),45000);await wait(()=>Date.now()-lastSound>1500);return{interruptAt,audioSeconds,statuses:events.slice(n).filter(e=>e.type==='response.done').map(e=>e.response.status),outputBufferEvents:events.slice(n).filter(e=>e.type.startsWith('output_audio_buffer')).map(e=>e.type)};});
await check('explicit hangup then new call without releasing lease',async()=>{const r=await req(location,'DELETE');assert([200,204,404].includes(r.status),'hangup HTTP '+r.status);await close();await p.waitForTimeout(1000);await connect();const end=await req(location,'DELETE');assert([200,204,404].includes(end.status),'final hangup HTTP '+end.status);await close();});
}catch(e){console.log('FAILED',String(e.message).replaceAll(key,'[redacted]'));process.exitCode=1;}
finally{await close();if(location)await req(location,'DELETE').catch(e=>console.log('CLEANUP_ERROR',e.name));await browser.close();server.close();rec.kill('SIGINT');await new Promise(r=>rec.on('exit',r));const pcm=Buffer.concat(audio),h=Buffer.alloc(44);h.write('RIFF');h.writeUInt32LE(pcm.length+36,4);h.write('WAVEfmt ',8);h.writeUInt32LE(16,16);h.writeUInt16LE(1,20);h.writeUInt16LE(1,22);h.writeUInt32LE(24000,24);h.writeUInt32LE(48000,28);h.writeUInt16LE(2,32);h.writeUInt16LE(16,34);h.write('data',36);h.writeUInt32LE(pcm.length,40);writeFileSync(out+'/speaker.wav',Buffer.concat([h,pcm]));writeFileSync(out+'/results.json',JSON.stringify(checks,null,2));writeFileSync(out+'/events.json',JSON.stringify(events,null,2));console.log('COMPLETE',checks.length,'checks');}
