import {createRequire} from 'node:module';import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
const require=createRequire('/home/tester/code/CopilotKit/OpenDots/package.json');const {chromium,devices}=require('playwright');
const root='/home/tester/evidence/integration-audit',out=root+'/receipt-final';mkdirSync(out,{recursive:true});const owner=JSON.parse(readFileSync(root+'/owner.json')).owner;const base='https://chriss-mac-mini.tail3127c0.ts.net:8444';const results=[];const log=console.log;console.log=(...a)=>log(...a.map(v=>typeof v==='string'?v.replaceAll(owner,'[redacted]'):v));
function assert(v,m){if(!v)throw new Error(m);}
async function create(denied=false){const b=await chromium.launch({headless:false,ignoreDefaultArgs:['--mute-audio'],args:denied?['--deny-permission-prompts']:[],env:{...process.env,PULSE_SOURCE:'jarvis_mic',PULSE_SINK:'voice_output'}});const ctx=await b.newContext({...devices['Pixel 7'],permissions:denied?[]:['microphone']});const p=await ctx.newPage();await p.addInitScript(()=>{window.lab={pcs:[],streams:[]};const native=navigator.mediaDevices.getUserMedia.bind(navigator.mediaDevices);navigator.mediaDevices.getUserMedia=async(...args)=>{const s=await native(...args);window.lab.streams.push(s);return s;};const RTC=window.RTCPeerConnection;window.RTCPeerConnection=class extends RTC{constructor(...a){super(...a);window.lab.pcs.push(this);}};});await p.goto(base);await p.getByRole('textbox',{name:'Owner access token'}).fill(owner);await p.getByRole('button',{name:'Unlock OpenDots',exact:true}).click();return{b,p,ctx};}
async function newChat(p){await p.getByRole('button',{name:'Open navigation',exact:true}).click();await p.getByRole('button',{name:'New chat',exact:true}).click();await p.getByRole('button',{name:'Start voice call',exact:true}).waitFor();}
async function connect(p){await newChat(p);await p.getByRole('button',{name:'Start voice call',exact:true}).click();await p.waitForFunction(()=>window.lab.pcs.some(pc=>pc.connectionState==='connected'),null,{timeout:40000});await p.getByRole('button',{name:'Mute microphone',exact:true}).waitFor();}
async function api(p,path,body){const r=await p.request.fetch(base+'/api'+path,{method:body===undefined?'GET':'POST',headers:{Authorization:'Bearer '+owner},...(body===undefined?{}:{data:body}),timeout:70000});assert(r.ok(),'API '+path+' returned '+r.status());return r.json();}
async function media(p){return p.evaluate(()=>({peers:window.lab.pcs.map(pc=>pc.connectionState),tracks:window.lab.streams.flatMap(s=>s.getTracks().map(t=>({enabled:t.enabled,readyState:t.readyState})))}));}
async function cleanup(p){const w=await api(p,'/workspace');for(const c of w.calls.filter(c=>['active','connecting'].includes(c.status)))await api(p,'/voice/calls/'+c.id+'/end',{transcript:'Fault-injection test cleanup.'});}
async function run(name,fn,denied=false){console.log('CASE',name);const {b,p}=await create(denied);try{const result=await fn(p);results.push({name,...result});console.log('RESULT',JSON.stringify(results.at(-1)));}catch(e){results.push({name,result:'TEST_ERROR',error:String(e.message).replaceAll(owner,'[redacted]')});console.log('TEST_ERROR',name,String(e.message));await p.screenshot({path:out+'/'+name+'-error.png',fullPage:true});}finally{await p.unrouteAll({behavior:'ignoreErrors'});try{await cleanup(p);}catch(e){console.log('CLEANUP_ERROR',String(e.message));}await b.close();writeFileSync(out+'/results.json',JSON.stringify(results,null,2));}}
await run('final-build-call-and-receipt',async p=>{const before=await api(p,'/workspace');await connect(p);const active=(await api(p,'/workspace')).calls.find(c=>c.status==='active');await p.getByRole('button',{name:'End voice call',exact:true}).last().click();await p.getByRole('button',{name:'Start voice call',exact:true}).waitFor({timeout:40000});const history=await api(p,'/copilotkit/threads/'+active.threadId+'/messages');const ack='Call ended. Transcript saved for this conversation; generated speech may have been interrupted.';assert(history.messages.some(m=>m.content===ack),'No deterministic receipt');const state=await media(p);assert(state.tracks.every(t=>t.readyState==='ended'),'Mic retained');await p.screenshot({path:out+'/receipt.png',fullPage:true});return{result:'PASS',threadId:active.threadId,dotId:active.dotId,state,receipt:ack};});
